function importfile()
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read
for i=1:201
arr=[];
%  Auto-generated by MATLAB on 28-Apr-2011 23:09:48
fileToRead1= [num2str(i) '.txt'];
i
% Import the file
newData1 = importdata(fileToRead1);
arr(:,:)=newData1.data(:,1:20);
xlswrite(num2str(i) ,arr);
end
% Create new variables in the base workspace from those fields.

end

